#:schema node_modules/wrangler/config-schema.json
name = "starter"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat_v2"]
main = "./server.ts"
workers_dev = true
# routes = [{ pattern = "theapiagency.com", custom_domain = true }]

# https://developers.cloudflare.com/workers/platform/compatibility-dates

# kv_namespaces = [{ binding = "cache", id = "cache" }]
[observability]
enabled = true


[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"


[build]
command = "bun run build"
